FROM openjdk:16-jdk-slim as builder
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract


FROM openjdk:16-jdk-slim

ARG SERVER_SSL_KEY_STORE_PASSWORD
ARG HOSTNAME
ENV SERVER_SSL_KEY_STORE_PASSWORD ${SERVER_SSL_KEY_STORE_PASSWORD}
ENV HOSTNAME ${HOSTNAME}

COPY --from=builder dependencies/ ./
COPY --from=builder snapshot-dependencies/ ./
COPY --from=builder spring-boot-loader/ ./
COPY --from=builder application/ ./
COPY self_signed.jks ./

USER root
COPY self_signed.pfx $JAVA_HOME/lib/security/self_signed.pfx
RUN $JAVA_HOME/bin/keytool -importkeystore -srckeystore $JAVA_HOME/lib/security/self_signed.pfx -srcstorepass ${SERVER_SSL_KEY_STORE_PASSWORD} -srcstoretype pkcs12 -srcalias ${HOSTNAME}_self_signed -destkeystore $JAVA_HOME/lib/security/cacerts -deststorepass changeit -destalias ${HOSTNAME}_self_signed
    
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]